<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.machanism.machai</groupId>
		<artifactId>machai</artifactId>
		<version>1.4.2-SNAPSHOT</version>
	</parent>
	<artifactId>machai-mcp-server</artifactId>
	<name>Machai MCP Server</name>
	<description>
		A server implementation for the Model Context Protocol (MCP) using the
		Machai AI framework.
		Provides integration with GenAI tools and supports both HTTP and STDIO
		interfaces for AI-powered tool execution and orchestration.
		Does not include its own tools for publication and requires
		the use of additional libraries implementing functional tools and
		prompts.
	</description>

	<profiles>
		<profile>
			<id>pack</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-assembly-plugin</artifactId>
						<configuration>
							<archive>
								<manifest>
									<mainClass>
										org.machanism.machai.mcp.server.McpServer</mainClass>
								</manifest>
								<manifestEntries>
									<Implementation-Version>${project.version}</Implementation-Version>
								</manifestEntries>
							</archive>
							<descriptorRefs>
								<descriptorRef>jar-with-dependencies</descriptorRef>
							</descriptorRefs>
							<appendAssemblyId>false</appendAssemblyId>
							<outputDirectory>
								${env.MACHANISM_PACK_DIR}/machai/${project.artifactId}/releases</outputDirectory>
						</configuration>
						<executions>
							<execution>
								<id>build-artifact</id>
								<phase>install</phase>
								<goals>
									<goal>single</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

	<properties>
		<maven.compiler.release>17</maven.compiler.release>
		<gw.acts />
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.javadoc.skip>false</maven.javadoc.skip>
		<plantuml-generator.scanPackages>org.machanism.machai.mcp.server*</plantuml-generator.scanPackages>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>5.9.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-inline</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.modelcontextprotocol.sdk</groupId>
			<artifactId>mcp</artifactId>
			<version>2.0.0-RC1</version>
		</dependency>
		<dependency>
			<groupId>org.machanism.machai</groupId>
			<artifactId>genai-client</artifactId>
			<version>1.4.2-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>commons-cli</groupId>
			<artifactId>commons-cli</artifactId>
			<version>1.11.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-text</artifactId>
			<version>1.15.0</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>12.1.9</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty.ee10</groupId>
			<artifactId>jetty-ee10-servlet</artifactId>
			<version>12.1.9</version>
		</dependency>
	</dependencies>

	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<configuration>
					<links>
						<link>
							https://docs.oracle.com/en/java/javase/11/docs/api/</link>
						<link>
							https://macha.machanism.org/core/core-commons/configurator/apidocs/</link>
						<link>
							https://machai.machanism.org/genai-client/apidocs/</link>
					</links>
				</configuration>
			</plugin>
		</plugins>
	</reporting>

	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<scm>
		<connection>scm:git:https://github.com/machanism-org/machai.git</connection>
		<developerConnection>scm:git:https://github.com/machanism-org/machai.git</developerConnection>
		<url>https://github.com/machanism-org/machai.git</url>
	</scm>

</project>
